exp_name: _400_epochs_NEW
mode: train
model:
  name: bim_rnet
  args:
    pyr_level: 3
    feat_channels: 32
train_dataset:
  name: vimeo
  args:
    root_path: C:/Users/ZVC/Downloads/Crucial/CS420/BiM-VFI/data/vimeo_triplet
    split: train
    patch_size: 128
  loader:
    batch_size: 4
    num_workers: 2
test_dataset:
  name: vimeo
  args:
    root_path: C:/Users/ZVC/Downloads/Crucial/CS420/BiM-VFI/data/vimeo_triplet
    split: val
  loader:
    batch_size: 4
    num_workers: 2
  save_imgs: false
optimizer:
  name: adamW
  args:
    lr: 5.0e-05
    weight_decay: 5.0e-05
lr_scheduler:
  name: step_lr
  args:
    step_size: 25
    gamma: 0.8
gradient_clip: 1
loss:
- name: multiple_charbonnier
  args:
    weight: 1
    gamma: 0.25
- name: multiple_ternary
  args:
    weight: 1
    gamma: 0.25
- name: photo_teacher
  args:
    weight: 1
    gamma: 0.25
- name: flow_distill_res
  args:
    weight: 0.005
    beta: 1
    gamma: 0.5
- name: flow_teacher_reg
  args:
    weight: 0.005
    gamma: 0.5
- name: flow_smooth_tea1
  args:
    weight: 0.05
    gamma: 0.5
    weight_type: gaussian
    edge_constant: 150
max_epoch: 400
validate_every: 10
save_every: 10
vis_every: 10
seed: 1234
dist_url: env://
enable_early_stopping: true
early_stopping_patience: 3
env:
  exp_name: bim_rnet_train_new__400_epochs_NEW
  save_dir: save\bim_rnet_train_new__400_epochs_NEW
  tot_gpus: 1
  cudnn: false
  port: '29600'
  wandb_upload: false
summary_dir: save\bim_rnet_train_new__400_epochs_NEW\summaries
checkpoint_dir: save\bim_rnet_train_new__400_epochs_NEW\checkpoints
output_dir: save\bim_rnet_train_new__400_epochs_NEW\output
log_dir: save\bim_rnet_train_new__400_epochs_NEW\logs
cfg_dir: save\bim_rnet_train_new__400_epochs_NEW\cfgs
run_description: train_vimeo_train
distributed: false
